/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DaoAssist;
import dao.DaoStaff;
import dao.impl.DaoAssistImpl;
import dao.impl.DaoStaffImpl;
import dto.Assist;
import dto.Staff;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SEVEN
 */
public class frmAssist extends javax.swing.JFrame {

    private DaoAssist daoAssist = new DaoAssistImpl();
    private DaoStaff daoStaff = new DaoStaffImpl();
    private int ass_state = 0;
    private int ass_id = 0;
    private String sta_fullname = "";

    /**
     * Creates new form frmAssist
     */
    public frmAssist() {
        initComponents();
        try {
            daoAssist.oppenAssist();
            showListStaff();
        } catch (Exception e) {
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        bSave = new javax.swing.JButton();
        tfStaCode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAssistStaff = new javax.swing.JTable();
        tfStaFullName = new javax.swing.JTextField();
        bStaff = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asistencia");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bSave.setBackground(new java.awt.Color(255, 255, 255));
        bSave.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bSave.setText("REGISTRAR");
        bSave.setName("btnSave"); // NOI18N
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        jPanel1.add(bSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 121, 54));

        tfStaCode.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tfStaCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfStaCode.setToolTipText("Código de usuario");
        tfStaCode.setEnabled(false);
        tfStaCode.setMargin(new java.awt.Insets(7, 10, 7, 10));
        tfStaCode.setName("txtStaCode"); // NOI18N
        jPanel1.add(tfStaCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 250, -1));

        tAssistStaff.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tAssistStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tAssistStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tAssistStaffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tAssistStaff);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 490, 440));

        tfStaFullName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tfStaFullName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfStaFullName.setToolTipText("Código de usuario");
        tfStaFullName.setEnabled(false);
        tfStaFullName.setMargin(new java.awt.Insets(7, 10, 7, 10));
        tfStaFullName.setName("txtStaCode"); // NOI18N
        jPanel1.add(tfStaFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 250, -1));

        bStaff.setBackground(new java.awt.Color(255, 255, 255));
        bStaff.setText("staff");
        bStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStaffActionPerformed(evt);
            }
        });
        jPanel1.add(bStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        String accept = "Aceptar";
        String cancel = "Cancelar";
        Object[] options = {accept, cancel};
        int result = 0;
        switch(ass_state){
            case 1:
                result = JOptionPane.showOptionDialog(this, " Deseas registrar assistencia ENTRADA de " + sta_fullname + "?", "Marcar assistencia de ENTRADA", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, cancel);
                break;
            case 2:
                result = JOptionPane.showOptionDialog(this, " Deseas registrar assistencia SALIDA de " + sta_fullname + "?", "Marcar assistencia de SALIDA", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, cancel);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Dia completado de " + sta_fullname);
               break;
        }
        if (result == 0) {
            if (daoAssist.assistSve(ass_id, ass_state)) {
                ass_state = 0;
                ass_id = 0;
                sta_fullname = "";
                showListStaff();
                cleanForm();
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar");
            }
        }
    }//GEN-LAST:event_bSaveActionPerformed

    private void bStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStaffActionPerformed
        dispose();

        frmStaff staff = new frmStaff();
        staff.setVisible(true);
        staff.setLocationRelativeTo(null);
    }//GEN-LAST:event_bStaffActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        showListStaff();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void tAssistStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tAssistStaffMouseClicked
        // TODO add your handling code here:
        ass_state = Integer.parseInt(tAssistStaff.getValueAt(tAssistStaff.getSelectedRow(), 6).toString());
        ass_id = Integer.parseInt(tAssistStaff.getValueAt(tAssistStaff.getSelectedRow(), 3).toString());
        sta_fullname = tAssistStaff.getValueAt(tAssistStaff.getSelectedRow(), 2).toString();
        tfStaCode.setText(tAssistStaff.getValueAt(tAssistStaff.getSelectedRow(), 1).toString());
        tfStaFullName.setText(tAssistStaff.getValueAt(tAssistStaff.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tAssistStaffMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAssist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAssist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAssist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAssist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAssist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSave;
    private javax.swing.JButton bStaff;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tAssistStaff;
    private javax.swing.JTextField tfStaCode;
    private javax.swing.JTextField tfStaFullName;
    // End of variables declaration//GEN-END:variables

    private void showListStaff() {
        List<Staff> list = null;
        list = daoStaff.staffList();
        Object[][] obj = new Object[list.size()][7];
        /*
        for (Staff staff : list) {
            System.err.println(staff.getSta_name());
        }
         */
        for (int i = 0; i < list.size(); i++) {
            obj[i][0] = list.get(i).getSta_id();
            obj[i][1] = list.get(i).getSta_code();
            obj[i][2] = list.get(i).getSta_surname().toUpperCase() + ", " + list.get(i).getSta_name();
            for (Assist assist : list.get(i).getAssist()) {
                obj[i][3] = assist.getAss_id();
                obj[i][4] = assist.getAss_time_input();
                obj[i][5] = assist.getAss_time_output();
                obj[i][6] = assist.getAss_state();
            }
        }

        Object[] columns = {"", "CÓDIGO", "APELLIDOS Y NOMBRES", "", "ENTRADA", "SALIDA", ""};
        DefaultTableModel model = new DefaultTableModel(obj, columns);
        tAssistStaff.setModel(model);

        tAssistStaff.getColumnModel().getColumn(0).setPreferredWidth(0);
        tAssistStaff.getColumnModel().getColumn(1).setPreferredWidth(50);
        tAssistStaff.getColumnModel().getColumn(2).setPreferredWidth(200);

        DefaultTableCellRenderer modelocentrar = new DefaultTableCellRenderer();
        modelocentrar.setHorizontalAlignment(SwingConstants.CENTER);
        tAssistStaff.getColumnModel().getColumn(0).setCellRenderer(modelocentrar);
        tAssistStaff.getColumnModel().getColumn(1).setCellRenderer(modelocentrar);
        tAssistStaff.getColumnModel().getColumn(3).setCellRenderer(modelocentrar);
        tAssistStaff.getColumnModel().getColumn(4).setCellRenderer(modelocentrar);

        tAssistStaff.getColumnModel().getColumn(0).setMinWidth(0);
        tAssistStaff.getColumnModel().getColumn(0).setMaxWidth(0);
        tAssistStaff.getColumnModel().getColumn(3).setMinWidth(0);
        tAssistStaff.getColumnModel().getColumn(3).setMaxWidth(0);
        tAssistStaff.getColumnModel().getColumn(6).setMinWidth(0);
        tAssistStaff.getColumnModel().getColumn(6).setMaxWidth(0);
    }

    private void cleanForm() {
        tfStaCode.setText("");
        tfStaFullName.setText("");
    }

}
