/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DaoStaff;
import dao.impl.DaoStaffImpl;
import dto.Staff;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SEVEN
 */
public class frmStaff extends javax.swing.JFrame {

    private DaoStaff daoStaff = new DaoStaffImpl();
    private Boolean edit = false;
    private int sta_id = 0;

    //private DaoStaff daoStaff = new DaoStaffImpl();
    /**
     * Creates new form frmStaff
     */
    public frmStaff() {
        initComponents();
        disableForm();
        try {
            showList("");
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bDelete1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tStaff = new javax.swing.JTable();
        tfStaSurname = new javax.swing.JTextField();
        tfStaCode = new javax.swing.JTextField();
        tfStaName = new javax.swing.JTextField();
        tfStaEmail = new javax.swing.JTextField();
        tfStaPhone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bSave = new javax.swing.JButton();
        bNew = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();
        bSearch = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        bAssist = new javax.swing.JButton();

        bDelete1.setText("ELIMINAR");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tStaff.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tStaff.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tStaff.setRowMargin(5);
        jScrollPane1.setViewportView(tStaff);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 311, 570, 280));

        tfStaSurname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfStaSurname.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jPanel1.add(tfStaSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 112, 155, -1));

        tfStaCode.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfStaCode.setEnabled(false);
        tfStaCode.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jPanel1.add(tfStaCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 51, 93, -1));

        tfStaName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfStaName.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jPanel1.add(tfStaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 112, 155, -1));

        tfStaEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfStaEmail.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jPanel1.add(tfStaEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 178, 155, -1));

        tfStaPhone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfStaPhone.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jPanel1.add(tfStaPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 178, 155, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 29, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Apellidos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 91, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nombres");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 91, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Correo electrónico");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 157, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Teléfono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 157, -1, -1));

        bSave.setBackground(new java.awt.Color(255, 255, 255));
        bSave.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bSave.setText("GUARDAR");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        jPanel1.add(bSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 112, 111, 58));

        bNew.setBackground(new java.awt.Color(255, 255, 255));
        bNew.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bNew.setText("NUEVO");
        bNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewActionPerformed(evt);
            }
        });
        jPanel1.add(bNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 100, -1));

        bEdit.setBackground(new java.awt.Color(255, 255, 255));
        bEdit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bEdit.setText("EDITAR");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        jPanel1.add(bEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 100, -1));

        bDelete.setBackground(new java.awt.Color(255, 255, 255));
        bDelete.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bDelete.setText("ELIMINAR");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(bDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 100, -1));

        tfSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfSearch.setMargin(new java.awt.Insets(5, 5, 5, 5));
        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchKeyReleased(evt);
            }
        });
        jPanel1.add(tfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 255, 572, -1));

        bSearch.setBackground(new java.awt.Color(255, 255, 255));
        bSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bSearch.setText("BUSCAR");
        bSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchActionPerformed(evt);
            }
        });
        jPanel1.add(bSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 100, -1));

        bCancel.setBackground(new java.awt.Color(255, 255, 255));
        bCancel.setText("CANCELAR");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        jPanel1.add(bCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 110, 30));

        bAssist.setBackground(new java.awt.Color(255, 255, 255));
        bAssist.setText("Assist");
        bAssist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAssistActionPerformed(evt);
            }
        });
        jPanel1.add(bAssist, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchActionPerformed
        String search = tfSearch.getText();
        cleanTable();
        showList(search);
    }//GEN-LAST:event_bSearchActionPerformed

    private void tfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyReleased
        String search = tfSearch.getText();
        if (search.length() > 3) {
            cleanTable();
            showList(search);
        }
    }//GEN-LAST:event_tfSearchKeyReleased

    private void bNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewActionPerformed
        tfStaCode.setText(daoStaff.staffGenerateCde());
        enableForm();
        edit = false;
    }//GEN-LAST:event_bNewActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        cleanForm();
        disableForm();
        edit = false;
    }//GEN-LAST:event_bCancelActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        Staff staff = new Staff();
        staff.setSta_code(tfStaCode.getText());
        staff.setSta_surname(tfStaSurname.getText());
        staff.setSta_name(tfStaName.getText());
        staff.setSta_email(tfStaEmail.getText());
        staff.setSta_phone_number(tfStaPhone.getText());
        if (edit) {
            staff.setSta_id(sta_id);
            if (daoStaff.staffUpd(staff)) {
                cleanForm();
                disableForm();
                showList("");
                sta_id = 0;
                edit = false;
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo modificar personal");
            }
        } else {
            if (daoStaff.staffIns(staff)) {
                cleanForm();
                disableForm();
                showList("");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo registrar personal");
            }
        }
    }//GEN-LAST:event_bSaveActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        int row = tStaff.getSelectedRow();
        if (row > -1) {
            Staff staff = daoStaff.staffGetById(Integer.parseInt(tStaff.getValueAt(row, 0).toString()));
            tfStaCode.setText(staff.getSta_code());
            tfStaSurname.setText(staff.getSta_surname());
            tfStaName.setText(staff.getSta_name());
            tfStaEmail.setText(staff.getSta_email());
            tfStaPhone.setText(staff.getSta_phone_number());
            enableForm();
            edit = true;
            sta_id = staff.getSta_id();
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione registro");
        }
    }//GEN-LAST:event_bEditActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        List<Integer> ids = null;
        ids = new LinkedList<>();
        int[] selection = tStaff.getSelectedRows();
        for (int i : selection) {
            int count = Integer.parseInt(tStaff.getValueAt(i, 0).toString());
            ids.add(count);
        }
        
        if (selection.length > 0) {
            /*Staff staff = daoStaff.staffGetById(Integer.parseInt(tStaff.getValueAt(row, 0).toString()));
            String accept = "Aceptar";
            String cancel = "Cancelar";
            Object[] options = {accept, cancel};
            int result = JOptionPane.showOptionDialog(this, " Deseas elimiar a " + staff.getSta_surname() + ", " + staff.getSta_name()+ "?", "Eliminar personal", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, cancel);
            if (result == 0) {
                if (daoStaff.staffDel(ids)) {
                    
                }
            }*/
            String accept = "Aceptar";
            String cancel = "Cancelar";
            Object[] options = {accept, cancel};
            int result = JOptionPane.showOptionDialog(this, " Deseas elimiar a personal?", "Eliminar personal", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, cancel);
            if (result == 0) {
                if (daoStaff.staffDel(ids)) {
                    showList("");
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar personal");
                }
            }
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bAssistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAssistActionPerformed
        dispose();

        frmAssist assist = new frmAssist();
        assist.setVisible(true);
        assist.setLocationRelativeTo(null);
    }//GEN-LAST:event_bAssistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAssist;
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bDelete1;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bNew;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tStaff;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfStaCode;
    private javax.swing.JTextField tfStaEmail;
    private javax.swing.JTextField tfStaName;
    private javax.swing.JTextField tfStaPhone;
    private javax.swing.JTextField tfStaSurname;
    // End of variables declaration//GEN-END:variables

    private void showList(String search) {
        List<Staff> list = null;
        list = daoStaff.staffQry(search);
        Object[][] obj = new Object[list.size()][7];
        for (int i = 0; i < list.size(); i++) {
            obj[i][0] = list.get(i).getSta_id();
            obj[i][1] = list.get(i).getSta_code();
            obj[i][2] = list.get(i).getSta_surname();
            obj[i][3] = list.get(i).getSta_name();
            obj[i][4] = list.get(i).getSta_email();
            obj[i][5] = list.get(i).getSta_phone_number();
            obj[i][6] = list.get(i).getSta_state();
        }

        Object[] columns = {"", "CODIGO", "APELLIDOS", "NOMBRES", "EMAIL", "TELEFONO", "ESTADO"};
        DefaultTableModel model = new DefaultTableModel(obj, columns);
        tStaff.setModel(model);

        tStaff.getColumnModel().getColumn(0).setPreferredWidth(0);
        tStaff.getColumnModel().getColumn(1).setPreferredWidth(80);
        tStaff.getColumnModel().getColumn(2).setPreferredWidth(130);
        tStaff.getColumnModel().getColumn(3).setPreferredWidth(130);
        tStaff.getColumnModel().getColumn(4).setPreferredWidth(150);
        tStaff.getColumnModel().getColumn(5).setPreferredWidth(80);
        tStaff.getColumnModel().getColumn(6).setPreferredWidth(100);

        /*
        for (int i = 0; i < list.size(); i++) {
            tStaff.setValueAt(list.get(i).getSta_id(), i, 0);
            tStaff.setValueAt(list.get(i).getSta_code(), i, 1);
            tStaff.setValueAt(list.get(i).getSta_surname(), i, 2);
            tStaff.setValueAt(list.get(i).getSta_name(), i, 3);
            tStaff.setValueAt(list.get(i).getSta_email(), i, 4);
            tStaff.setValueAt(list.get(i).getSta_phone_number(), i, 5);
            tStaff.setValueAt(list.get(i).getSta_state(), i, 6);
        }
         */
    }

    private void cleanTable() {
        for (int row = 0; row < tStaff.getRowCount(); row++) {
            for (int col = 0; col < tStaff.getColumnCount(); col++) {
                tStaff.setValueAt("", row, col);
            }
        }
    }

    private void cleanForm() {
        tfStaCode.setText("");
        tfStaSurname.setText("");
        tfStaName.setText("");
        tfStaEmail.setText("");
        tfStaPhone.setText("");
    }

    private void enableForm() {
        tfStaSurname.setEnabled(true);
        tfStaName.setEnabled(true);
        tfStaEmail.setEnabled(true);
        tfStaPhone.setEnabled(true);
        bSave.setEnabled(true);
        bCancel.setEnabled(true);
    }

    private void disableForm() {
        tfStaSurname.setEnabled(false);
        tfStaName.setEnabled(false);
        tfStaEmail.setEnabled(false);
        tfStaPhone.setEnabled(false);
        bSave.setEnabled(false);
        bCancel.setEnabled(false);
    }
}
